### ISSUE TITLE
TS types

### ISSUE THREAD

**Issue by Nonolanlan1007** [DiscordAnalytics/node-package#1]
les types ne fonctionnent pas

**Comment by ValDesign22** [comment]
C'est quoi exactement le prob avec les types?

**Comment by Nonolanlan1007** [comment]
l'IDE ne trouve pas les types correspondant au module. Donc pour le moment je met un @ts-ignore x)

![image.png](https://volta.s3.fr-par.scw.cloud/image_90c85915c6.png)

**Comment by ValDesign22** [comment]
fait chier, faut que je setup les types avec un .d.ts

**Comment by Nonolanlan1007** [comment]
Ou plutôt tu patch ce que j'avais fait 🤣

**Comment by ValDesign22** [comment]
comment ça?

**Comment by Nonolanlan1007** [comment]
Ok je teste ça !
